### ISSUE TITLE
A kind request for the code of sound field rendering in Sounding Bodies.

### ISSUE THREAD

**Issue by fumyou13** [facebookresearch/SoundingBodies#1]
Thanks for your great work.

Since I'm not very familiar with sound field rendering and the literature mentioned doesn't provide samples of the corresponding implementations, I'd sincerely appreciate it if you could provide the code for this part (Eq.6 and Eq.10).

Thanks in advance.

**Comment by dejanm07** [comment]
For training and evaluating the proposed network architecture the sound field rendering equations are not needed (the network works directly on the microphone waveforms). The sound field rendering equations are necessary for subsequent post-processing such as sound field visualization or for transforming the predicted sound field into binaural signals. For the visualizations shown in the paper we used a MATLAB implementation that is not in a publishable state (it is tailored for the specific capture system setup and is not easy to use). We may provide Python implementation in future as a part of follow-up works.
